### ISSUE TITLE
500 internal error entrando in campagna appio, fino a pochi giorni fa funzionava

### ISSUE THREAD

**Issue by RafMal77** [teamdigitale/apportafoglio#111]
500 internal error entrando in campagna appio, fino a pochi giorni fa funzionava

**Comment by fmancinidtd** [comment]
Gentilmente si può riprovare per capire se è stato risolto? Grazie

**Comment by RafMal77** [comment]
No, purtroppo c'è la stessa situazione, sembra che la richiesta vada in timeout e si ottiene sempre 500 internal error. Raffaele Malfer

**Comment by fmancinidtd** [comment]
Ora dovrebbe essere ok

**Comment by RafMal77** [comment]
CONFERMO!

Ora è ok

Grazie

Ciao

 

Raffaele 

 

Da: fausto mancini ***@***.***> 
Inviato: giovedì 27 giugno 2024 16:10
A: teamdigitale/apportafoglio ***@***.***>
Cc: Raffaele Malfer ***@***.***>; Author ***@***.***>
Oggetto: Re: [teamdigitale/apportafoglio] 500 internal error entrando in campagna appio, fino a pochi giorni fa funzionava (Issue #111)

 

Ora dovrebbe essere ok
