### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by pasto-dev** [teamdigitale/apportafoglio#93]
Ciao, nel ribadire i complimenti per l'app molto utile segnalo che entrando nel dettaglio (da consulta enti) degli enti mi compare l'errore 550 internal error. Questo per tutti gli enti che ho provato a selezionare.
grazie Roberto Pastorino account manager area NO2

**Comment by fmancinidtd** [comment]
Ciao, è quasi certamente un problema legato alle autorizzazioni degli oggetti su SalesForce. In verifica.

**Comment by pasto-dev** [comment]
Buongiorno, segnalo la risoluzione dell'errore su Enti mentre rimangono errori 500 internal error su https://[apportafoglio.vercel.app/monitoraggio/proroghe/monitoraggio], su https://[apportafoglio.vercel.app/cruscotti/generale] e su https://[apportafoglio.vercel.app/op/contatti]. grazie

**Comment by pasto-dev** [comment]
buongiorno, anche andando nel dettaglio delle scadenze ho internal error ad esempio comune di Tiglieto https://[apportafoglio.vercel.app/op/candidatura/a037Q000009y2UWQAY]

**Comment by fmancinidtd** [comment]
Dovrebbe essere risolto con la corretta configurazione dei permessi su SF
