### ISSUE TITLE
Errore 500

### ISSUE THREAD

**Issue by rmozzillo-dtd** [teamdigitale/apportafoglio#95]
Ciao Fausto, anche io ho lo stesso errore 500 segnalato da altri colleghi quando cerco di entrare in qualche scheda di dettaglio. Segnalo la stessa cosa anche per conto di una mia collega, Sara Guttilla. Siamo entrambi del Team Nord-Est. Attendo tue
Grazie
Roberto

**Comment by rmozzillo-dtd** [comment]
Aggiungo alla segnalazione anche il collega Iacopo Portunato

**Comment by gardinid** [comment]
idem anche per me Diego Gardini

**Comment by paolocamuti** [comment]
Ho lo stesso problema su diverse funzioni: Paolo Camuti Borani

**Comment by fmancinidtd** [comment]
Dovrebbe essere risolto con la corretta configurazione dei permessi su SF

**Comment by paolocamuti** [comment]
Ciao Fausto,
ti evidenzio in dettaglio dove riscontro tuttora Errore500:
Menù Cruscotti-->Generale
Menù Monitoraggio-->Proroghe
Menù Consulta-->Report Accounting
Dalla pagina Scadenze, a fianco di ogni scadenza clicco sull'icona "lente +" in fondo alla riga a dx
Dalla pagina Scheda ente, sezione Scadenziario, clicco sull'icona "lente +" in fondo alla riga a dx
Dalla pagina Scheda ente, sezione Referenti Attivi, clicco sull'icona "download"
