### ISSUE TITLE
Vista limitata, non vedo le campagne

### ISSUE THREAD

**Issue by danieleamurri** [teamdigitale/apportafoglio#96]
ecco quello che vedo:
![Screenshot 2024-05-21 alle 13 17 25](https://github.com/teamdigitale/apportafoglio/assets/6347554/3cde0dff-dc37-41cb-8581-a28372f36c60)

**Comment by fmancinidtd** [comment]
Ciao Daniele,
questo avviene perché su Salesforce non sei assegnato a nessun ente, cioè non sei né account manager né technical implementation manager di alcun ente
